import Image from "next/image";
import { Icon } from "@/components/ui/Icon";
export function AboutSection() {
  return <section id="perfil" className="section-space about-section" aria-labelledby="about-heading"><div className="page-shell about-layout">
    <figure className="about-photo" data-motion="image"><Image src="/images/diego_walking_hq.png" alt="Diego García caminando frente al Congreso de la República" fill sizes="(max-width: 800px) 100vw, 46vw" unoptimized /><figcaption>De Casanare al Congreso de la República.</figcaption></figure>
    <div className="about-copy"><h2 id="about-heading" data-motion="lines" aria-label="Una historia que empieza en Casanare."><span className="motion-line"><span className="motion-line-inner">Una historia que</span></span><span className="motion-line"><span className="motion-line-inner">empieza en <span>Casanare.</span></span></span></h2><p className="text-lead" data-motion="copy">Diego García lleva en el corazón la tierra que lo vio nacer.</p><p>Orgullosamente casanareño, representa una nueva generación de líderes comprometidos con el servicio público, el desarrollo regional y la construcción de oportunidades para el territorio.</p><p>Su historia está profundamente ligada a Casanare, una tierra que le enseñó el valor de la palabra, la fuerza del trabajo y la importancia de construir comunidad.</p>
    <div className="biography-details" data-motion="copy"><details><summary>Formación y preparación<span className="expand-icon" aria-hidden="true" /></summary><div><p>Es profesional en Gobierno y Relaciones Internacionales, con Maestría en Gobierno y Políticas Públicas de la Universidad Externado de Colombia.</p><p>Cuenta con estudios de formación complementaria en la Universidad de Columbia. Su preparación académica se ha enfocado en el análisis de los asuntos públicos, el desarrollo territorial y la construcción de políticas que generen impacto real.</p></div></details><details><summary>Trayectoria y compromiso<span className="expand-icon" aria-hidden="true" /></summary><div><p>Convencido de que los grandes cambios se logran escuchando a la gente y trabajando de la mano con los ciudadanos.</p><p>Ha dedicado su trayectoria a servir al territorio desde distintos escenarios académicos, institucionales y políticos, entendiendo que el progreso se construye entre todos.</p></div></details></div><a href="#gestion" className="text-link">Conoce el trabajo legislativo <Icon /></a></div>
  </div></section>;
}

